### ISSUE TITLE
Split direction in triangulation functions

### ISSUE THREAD

**Issue by brilletjuh** [opentomb/TRosettaStone3#8]
In section 4.4.7, the triangulation-functions, just below the different types illustration, the described functions are somewhat confusing when in comes to the mentioned directions.
0x07/... mentions nw/se, but below it says sw/ne
0x08/... mentions ne/sw, but below sw/nw
0x09/... mentions just nw, but below sw/ne
0x0a/... mentions just ne, but below nw/se

**Comment by stohrendorf** [comment]
I'm confused, are you referring to the pictures? If that's the case, the pictures are probably wrong. If you're referring to text, please provide quotes, so it's easier to find. As far as I can tell (assuming I'm not blind), there's nothing matching your description except for the pictures. The corresponding file you're referring to is most likely https://github.com/opentomb/TRosettaStone3/blob/d27d77a738e41be539b4f4022a6e8ad28a32d829/floordata.asc.

**Comment by brilletjuh** [comment]
I was talking about that file with the floordata, but not about the pictures, but about the text below the pictures, specifically this section:
https://github.com/opentomb/TRosettaStone3/blob/master/floordata.asc#functions-0x07-0x0b-0x0c
https://postimg.cc/0zvfT6cg
I have highlighted what I was talking about. sorry for the confusion in my first post.
